[project]
name = "dsala"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gspread>=6.1.3",
    "pyyaml>=6.0.2",
    "sqlalchemy>=2.0.36",
]
